version: '3'


services:
  
  rabbitmq:
    build: .
    image: mqtt-rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"

  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    ports:
      - "9999:9999"
    # environment:
    #   - INFLUXDB_DB=${INFLUXDB_DB}
    #   - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
    #   - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}